## why do we use python numpy?

* we used python numpy array instead of list bcz of the three reasons:
> - Less memory
> - Fast
> - Convenient to understand 
> - vectorization(way faster than for loop in list)

# Numpy stands for "Numerical Python"

# numpy is one of the most foundational packages for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. The name "NumPy" stands for "Numerical Python," reflecting its purpose as a library for numerical computations. 

# it is an open source that is widely used in scientific computing, data analysis, and machine learning. NumPy is designed to be fast and efficient, making it a popular choice for handling large datasets and performing complex mathematical operations.
# the numpy library contains multi dimension array data structures such as homogeneous  n dimension arrays, which allow for efficient storage and manipulation of numerical data. It also includes a wide range of mathematical functions, linear algebra operations, random number generation, and tools for integrating with other libraries and frameworks. NumPy's array-oriented computing capabilities make it a fundamental building block for many scientific and engineering applications in Python.



# why not python in build
* a pythin list plus meta date plus pointer -> uses more memory 
* a numpy array stores data a continous block -> more efficient and compact

# difference b/w list and array
list is a in build 
memory usage

In [3]:
import numpy 
x = numpy.array([1, 2, 3, 4, 5])
print(x , type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [11]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print(x , type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
import numpy as np
np.__version__

'2.5.2'

In [12]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
# tuple to array
t = (1, 2, 3, 4, 5)
arr = np.array(t)
arr

array([1, 2, 3, 4, 5])

In [18]:
# dictionary to array
dictionary = {'a':1, 'b':2, 'c':3}
arr = np.array(dictionary)
arr

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [19]:
# list to array
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [21]:
# set to array
s = {1, 2, 3, 4, 5}
arr = np.array(s)
arr

array({1, 2, 3, 4, 5}, dtype=object)

In [ ]:
# #dimension array
arr= np.array(100)
print(arr)
print(arr.ndim)
print(type(arr))

100
0
<class 'numpy.ndarray'>


In [ ]:
oneD = np.array([1,2,3,4,5])

print(oneD)

# attribute of array
print(oneD.ndim)      # dimension of array
print(oneD.shape)     # shape of the array in row or column
print(oneD.size)      # number of elements in the numpy array
print(oneD.itemsize)  # size in bytes of each element 
print(oneD.dtype)     # datatype of the element


[1 2 3 4 5]
1
(5,)
5
8
int64


In [24]:
# Creating 2-dimensional ndarray
from numpy import size


twoD = np.array([[1,2,3],[4,5,6]])

print(twoD)

print(twoD.ndim)  
print(twoD.shape)   
print(twoD.size)    
print(twoD.itemsize)    
print(twoD.dtype) 

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


In [ ]:
import numpy as np
threeD = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(threeD)

print(threeD.ndim)
print(threeD.shape)
print(threeD.size)
print(threeD.itemsize)
print(threeD.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
8
int64


In [26]:
# creating np.array with all elements as zero
import numpy as np
x=np.zeros((3,4),dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
