## why do we use python numpy?

* we used python numpy array instead of list bcz of the three reasons:
> - Less memory
> - Fast
> - Convenient to understand 
> - vectorization(way faster than for loop in list)

# Numpy stands for "Numerical Python"

# numpy is one of the most foundational packages for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. The name "NumPy" stands for "Numerical Python," reflecting its purpose as a library for numerical computations. 

# it is an open source that is widely used in scientific computing, data analysis, and machine learning. NumPy is designed to be fast and efficient, making it a popular choice for handling large datasets and performing complex mathematical operations.
# the numpy library contains multi dimension array data structures such as homogeneous  n dimension arrays, which allow for efficient storage and manipulation of numerical data. It also includes a wide range of mathematical functions, linear algebra operations, random number generation, and tools for integrating with other libraries and frameworks. NumPy's array-oriented computing capabilities make it a fundamental building block for many scientific and engineering applications in Python.



# why not python in build
* a pythin list plus meta date plus pointer -> uses more memory 
* a numpy array stores data a continous block -> more efficient and compact

# difference b/w list and array
list is a in build 
memory usage

In [3]:
import numpy 
x = numpy.array([1, 2, 3, 4, 5])
print(x , type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [11]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print(x , type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
import numpy as np
np.__version__

'2.5.2'

In [12]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
# tuple to array
t = (1, 2, 3, 4, 5)
arr = np.array(t)
arr

array([1, 2, 3, 4, 5])

In [18]:
# dictionary to array
dictionary = {'a':1, 'b':2, 'c':3}
arr = np.array(dictionary)
arr

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [19]:
# list to array
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [21]:
# set to array
s = {1, 2, 3, 4, 5}
arr = np.array(s)
arr

array({1, 2, 3, 4, 5}, dtype=object)

In [ ]:
# #dimension array
arr= np.array(100)
print(arr)
print(arr.ndim)
print(type(arr))

100
0
<class 'numpy.ndarray'>


In [ ]:
oneD = np.array([1,2,3,4,5])

print(oneD)

# attribute of array
print(oneD.ndim)      # dimension of array
print(oneD.shape)     # shape of the array in row or column
print(oneD.size)      # number of elements in the numpy array
print(oneD.itemsize)  # size in bytes of each element 
print(oneD.dtype)     # datatype of the element


[1 2 3 4 5]
1
(5,)
5
8
int64


In [24]:
# Creating 2-dimensional ndarray
from numpy import size


twoD = np.array([[1,2,3],[4,5,6]])

print(twoD)

print(twoD.ndim)  
print(twoD.shape)   
print(twoD.size)    
print(twoD.itemsize)    
print(twoD.dtype) 

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


In [ ]:
import numpy as np
threeD = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(threeD)

print(threeD.ndim)
print(threeD.shape)
print(threeD.size)
print(threeD.itemsize)
print(threeD.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
8
int64


In [26]:
# creating np.array with all elements as zero
import numpy as np
x=np.zeros((3,4),dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [1]:
# creating np.array with all elements as one
import numpy as np
x=np.ones((3,4),dtype=int)
print(x)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
# creating np.array with all elements as second

x=np.full((3,4), 2, dtype=int)
print(x)


[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [10]:
# starting value, ending value, step size
np.linspace(0, 10, 20)


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
# efficient storage and comptation
import numpy as np
import sys

list = [1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(list))
# sys.getsizeof() returns only the size of the list object, not the elements
arr = np.array(list)

# alternate
print(sys.getsizeof(arr))      
print(arr.nbytes)


136
184
72


In [12]:
# Faster than list
import numpy as np
import time

l1 =range(1,1000000)
l2 = range(1,1000000)
A1 = np.array(l1)
A2 = np.array(l2)

# operation to be performed on list
start = time.time()
result1 =[x+y for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

95.6418514251709


In [3]:
#vectorised addition
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)

[11 22 33]


In [8]:
import numpy as np
arr = np.arange(100000)
lst = [x for x in range(100000)]
# python list
start = time.time()
lst2 = [x*2 for x in list]
end = time.time()
print(end-start)

#numpy array
start1 = time.time()
arr2 = arr * 2  #victorized
end1 = time.time()
print(end1-start1)

NameError: name 'time' is not defined

In [ ]:
#Vectorized multiplication
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a*b)

[10 40 90]


## BroadCasting 
* Operation between different shape arrays
* Numpy automatically expands the smaller array (without copying) so shapes becomes compatible

In [10]:
arr = np.array([1,2,3])  # shape (1,3)
vec = np.array([[1],[2],[3]])  # shape (3,1)
print(arr+vec)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# very imporatant question
## How to use Python numpy to get generate Random Number

* Random Module

1. numpy.random.rand()


In [ ]:
import numpy as np

x = np.random.rand(10)  #old API

print(x)

[0.53302804 0.06105013 0.58180507 0.50300351 0.01572154 0.50223018
 0.90314837 0.76377895 0.29042096 0.8245703 ]


In [ ]:
rng = np.random.default_rng()  #new API

x = n

2 numpy.random.randint()


In [14]:
import numpy as np
rng = np.random.default_rng()
x = np.random.randint(5,10,size=10)
y = rng.integers(5,10,size=10)
print(x)
print(y)

[8 7 9 8 5 6 6 6 9 6]
[8 5 5 7 5 7 6 8 9 5]
