## why do we use python numpy?

* we used python numpy array instead of list bcz of the three reasons:
> - Less memory
> - Fast
> - Convenient to understand 
> - vectorization(way faster than for loop in list)

# Numpy stands for "Numerical Python"

# numpy is one of the most foundational packages for numerical computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently. The name "NumPy" stands for "Numerical Python," reflecting its purpose as a library for numerical computations. 

# it is an open source that is widely used in scientific computing, data analysis, and machine learning. NumPy is designed to be fast and efficient, making it a popular choice for handling large datasets and performing complex mathematical operations.
# the numpy library contains multi dimension array data structures such as homogeneous  n dimension arrays, which allow for efficient storage and manipulation of numerical data. It also includes a wide range of mathematical functions, linear algebra operations, random number generation, and tools for integrating with other libraries and frameworks. NumPy's array-oriented computing capabilities make it a fundamental building block for many scientific and engineering applications in Python.



# why not python in build
* a pythin list plus meta date plus pointer -> uses more memory 
* a numpy array stores data a continous block -> more efficient and compact

# difference b/w list and array
list is a in build 
memory usage

In [13]:
import numpy 
x = numpy.array([1, 2, 3, 4, 5])
print(x , type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [11]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print(x , type(x))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
import numpy as np
np.__version__

'2.5.2'

In [12]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [16]:
# tuple to array
t = (1, 2, 3, 4, 5)
arr = np.array(t)
arr

array([1, 2, 3, 4, 5])

In [18]:
# dictionary to array
dictionary = {'a':1, 'b':2, 'c':3}
arr = np.array(dictionary)
arr

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

In [19]:
# list to array
l = [1, 2, 3, 4, 5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [21]:
# set to array
s = {1, 2, 3, 4, 5}
arr = np.array(s)
arr

array({1, 2, 3, 4, 5}, dtype=object)

In [ ]:
# #dimension array
arr= np.array(100)
print(arr)
print(arr.ndim)
print(type(arr))

100
0
<class 'numpy.ndarray'>


In [ ]:
oneD = np.array([1,2,3,4,5])

print(oneD)

# attribute of array
print(oneD.ndim)      # dimension of array
print(oneD.shape)     # shape of the array in row or column
print(oneD.size)      # number of elements in the numpy array
print(oneD.itemsize)  # size in bytes of each element 
print(oneD.dtype)     # datatype of the element


[1 2 3 4 5]
1
(5,)
5
8
int64


In [24]:
# Creating 2-dimensional ndarray
from numpy import size


twoD = np.array([[1,2,3],[4,5,6]])

print(twoD)

print(twoD.ndim)  
print(twoD.shape)   
print(twoD.size)    
print(twoD.itemsize)    
print(twoD.dtype) 

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


In [ ]:
import numpy as np
threeD = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(threeD)

print(threeD.ndim)
print(threeD.shape)
print(threeD.size)
print(threeD.itemsize)
print(threeD.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12
8
int64


In [26]:
# creating np.array with all elements as zero
import numpy as np
x=np.zeros((3,4),dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [1]:
# creating np.array with all elements as one
import numpy as np
x=np.ones((3,4),dtype=int)
print(x)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
# creating np.array with all elements as second

x=np.full((3,4), 2, dtype=int)
print(x)


[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [10]:
# starting value, ending value, step size
np.linspace(0, 10, 20)


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [ ]:
# efficient storage and comptation
import numpy as np
import sys

list = [1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(list))
# sys.getsizeof() returns only the size of the list object, not the elements
arr = np.array(list)

# alternate
print(sys.getsizeof(arr))      
print(arr.nbytes)


136
184
72


In [12]:
# Faster than list
import numpy as np
import time

l1 =range(1,1000000)
l2 = range(1,1000000)
A1 = np.array(l1)
A2 = np.array(l2)

# operation to be performed on list
start = time.time()
result1 =[x+y for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

95.6418514251709


In [3]:
#vectorised addition
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a+b)

[11 22 33]


In [ ]:
import numpy as np
arr = np.arange(100000)
lst = [x for x in range(100000)]
# python list
start = time.time()
lst2 = [x*2 for x in list]
end = time.time()
print(end-start)

#numpy array
start1 = time.time()
arr2 = arr * 2  #victorized
end1 = time.time()
print(end1-start1)





List time: 0.005434 seconds
NumPy time: 0.000543 seconds


In [ ]:
#Vectorized multiplication
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
print(a*b)

[10 40 90]


## BroadCasting 
* Operation between different shape arrays
* Numpy automatically expands the smaller array (without copying) so shapes becomes compatible

In [10]:
arr = np.array([1,2,3])  # shape (1,3)
vec = np.array([[1],[2],[3]])  # shape (3,1)
print(arr+vec)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# very imporatant question
## How to use Python numpy to get generate Random Number

* Random Module

1. numpy.random.rand()


In [ ]:
import numpy as np

x = np.random.rand(10)  #old API

print(x)

[0.53302804 0.06105013 0.58180507 0.50300351 0.01572154 0.50223018
 0.90314837 0.76377895 0.29042096 0.8245703 ]


In [ ]:
rng = np.random.default_rng()  #new API

x = n

2 numpy.random.randint()


In [14]:
import numpy as np
rng = np.random.default_rng()
x = np.random.randint(5,10,size=10)
y = rng.integers(5,10,size=10)
print(x)
print(y)

[8 7 9 8 5 6 6 6 9 6]
[8 5 5 7 5 7 6 8 9 5]


In [4]:
#The choice() method
# *Generate randdom numbers from array
rng = np.random.default_rng()

x = np.random.choice([1,2,3,4,5,6,7,8])
y = rng.choice([1,2,3,4,5,6,7,8])
print(x)
print(y)


2
2


In [5]:
rng = np.random.default_rng()

x = np.random.choice([1,2,3,4,5,6,7,8],size=(2,2))
y = rng.choice([1,2,3,4,5,6,7,8],size=2)
print(x)
print(y)

[[5 8]
 [6 6]]
[5 8]


In [7]:
#accessing elements from array

x = np.array([10,23,45,67,89])
x[2]
x[0:2] 

array([10, 23])

In [ ]:
# Multidimensional array
y = np.array([[12,23,34],[2,4,67]])
#metod 1
y[0,2]
#method 2
y[0][2]

np.int64(34)

In [14]:
#Basic slicing
x = np.array([10,23,45,67,89])
x[1:4]

array([23, 45, 67])

In [21]:
y = np.array([[1,2,3],[4,5,6],[2,2,2]])
y[1:]

y[-1:]

y[-3,-1]

np.int64(3)

In [26]:
#All item from column onward

y = np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])
y[0:2,1:]
y[:, 1:]

array([[23, 34],
       [ 4, 67],
       [ 1,  1],
       [ 2,  2]])

In [27]:
y = np.array([[12,23,34],[2,4,67],[1,1,1],[2,2,2]])

print(y[:, 1])

[23  4  1  2]


In [29]:
import numpy as np
arr = np.array([1,2,3,4])
s = arr[1:3]
s[0] = 100
print (arr)
print(s)
print(s.base)

[  1 100   3   4]
[100   3]
[  1 100   3   4]


 Fancy Indexing  

In [12]:
import numpy as np
xy = np.random.randint(2,100, size=(10,10))
xy1 = np.random.rand(10,10)
print(xy)
print(xy1)
print(xy[[1,3,6],[2,7,9]])



[[45 35  8 30 72 83 66 56 18 72]
 [53 77 29 22 68 94 83 50 11 25]
 [11 58 91 80 72 60 99 48 12 50]
 [46 35 10 32 32 97 45 58 64 41]
 [71 29 71 60 65 45 51 36 29 47]
 [32 64 73 25 74 10 74 56 15 21]
 [13  5 67 43  8 47 79 14 65 85]
 [31 98 31 22 32  9 94 27 55 37]
 [20 20 54 33 32 51  2 19 93  5]
 [55 83 93 10 95 79 41 17 19 59]]
[[0.53143514 0.80867596 0.26088961 0.33079133 0.36818814 0.87670503
  0.70495723 0.24835361 0.92610772 0.84310728]
 [0.14360124 0.07053271 0.31361357 0.50271353 0.76192761 0.38915345
  0.94881936 0.30210873 0.73861597 0.59242232]
 [0.21870612 0.5713401  0.08819167 0.97064915 0.00448338 0.1742318
  0.04712165 0.68493817 0.30847164 0.77002388]
 [0.86696626 0.10602239 0.41586141 0.96608993 0.89517617 0.98849076
  0.15760409 0.33984745 0.25157507 0.54037754]
 [0.59688895 0.42133505 0.78818265 0.06895201 0.35158293 0.21449614
  0.68710114 0.38503582 0.5879111  0.22891605]
 [0.75852201 0.13847847 0.35702154 0.36256597 0.7658001  0.56054234
  0.01071378 0.07340779 0.1

In [ ]:
import numpy as np
x[:,[1,3,5]]


x[1:7,]

# Re Shaping of array
* Transporting arrays
* Rotation of array
* joining of array
* splitting of arrays
* Data types for 

In [2]:
# Reshape
import numpy as np
n = np.arange(1,13)
print(n)
x = n.reshape((3,4))
print(x)
print(x.reshape(-1))


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# Check it Returns a Copy or View ?

In [ ]:
# Check if the returned array is a copy or a view
n = np.arange(1,13)
n[5]=20
print(n)
id(n)

[ 1  2  3  4  5 20  7  8  9 10 11 12]


2529186328720

In [ ]:
y = n.reshape((4,3)).base
print(y)
id(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


1385055811696

In [6]:
arr = np.array([1,2,3,4,5])
x = arr.view()
y = arr.copy()
arr[0] = 42

# Original Value
print(arr)
id(arr)



[42  2  3  4  5]


1385126542576

In [7]:
print(x)
print(id(x))
print(x.base)

[42  2  3  4  5]
1385126928784
[42  2  3  4  5]


In [8]:
print(y)
print(id(y))
print(y.base)

[1 2 3 4 5]
1385126542672
None


# Check if Array Owns its Data

In [ ]:
arr = np.array([1,2,3,4,5])


# Flatteninig Of Arrays

In [9]:
x = np.random.randint(10,size=(2,3))
print(x)
x.reshape(-1)

[[7 7 0]
 [5 5 6]]


array([7, 7, 0, 5, 5, 6], dtype=int32)

# Transposing Arrays

In [ ]:
x = np.arange(1,10).reshape(3,3)
print(x)
x.T            # this is the way to transpose the array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Rotation of Array
This is rot90() function is used to roatate an array by 90 degrees in the plane specified by axes


#### Syntax - 
  numpy.rot90(m,k=1,axes=(0,1))
  *m   Array of the or more dimensions.
  *k   Number of times the array is rotated by 90 degrees
  *axes The array is rotated in the plane defined by the axes.

In [ ]:
m = np.array([[1,2],[3,4],[6,5]])
np.rot90(m,k=3,axes=(0,1))


array([[6, 3, 1],
       [5, 4, 2]])

# Joining of Array
* np.concatenate
* np.vstack
* np.hstack

# Joining 2D Arrays

In [7]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y],axis=0)


array([1, 2, 3, 4, 5, 6])

In [9]:
x = np.array([[1,1,1],[2,2,2]])
y = np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=0)

array([[1, 1, 1],
       [2, 2, 2],
       [4, 4, 4],
       [5, 5, 5]])

In [12]:
x = np.array([[1,1,1],[2,2,2]])
y = np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=1)

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5]])

# Some Error

In [ ]:
# different dimension ki wajah se error hogi
import numpy as np
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
y = np.array([[4,4,4],[5,5,5]])
np.concatenate([x,y],axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

# np.Vstack

In [15]:
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
y = np.array([[4,4,4],[5,5,5]])
np.vstack([x,y])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

# np.hstack

In [16]:
x = np.array([[1,1,1],[2,2,2]])
y = np.array([[4,4,4],[5,5,5]])
np.hstack([x,y])

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5]])

# np.split

* np.split
* np.hsplit
* np.vsplit

In [ ]:
x = np.arange(1,13)
print (x)

np.split(x,4)
# zero par sirf axis hoga but 1 par nahi hoga

[ 1  2  3  4  5  6  7  8  9 10 11 12]


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [ ]:
# split [0:3],[3:5],[5:7],
x = np.arange(1,8)
print(x)
np.split(x,[3,5,7])

[1 2 3 4 5 6 7]


[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([], dtype=int64)]

# numpy .hsplit

In [23]:
x = np.arange(1,10).reshape([3,3])
print(x)

np.hsplit(x,3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [25]:
x = np.arange(1,11).reshape([2,5])
print(x)

np.hsplit(x,[1,2,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[ 4,  5],
        [ 9, 10]])]

# numpy.Vsplit

In [26]:
x = np.arange(1,11).reshape([5,2])
print(x)

np.vsplit(x,[4])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10]])]

# Data Types for ndarrays

bool_
int_
intc


# Casting

In [29]:
x = np.array([1,2,3,4])
print(x.dtype)
print(x)

y = x.astype(np.float64)
print(y.dtype)
print(y)

int64
[1 2 3 4]
float64
[1. 2. 3. 4.]


In [ ]:
x = np.array([1,2,2,3,4,5])
print(x)
print(x.dtype)

y = x.astype(np.int132)
print(y.dtype)
print(y)

[1 2 2 3 4 5]
int64


AttributeError: module 'numpy' has no attribute 'int132'

In [ ]:
x = np.array(['5.6','23.3','4.5'],dtype=np.strings)

In [31]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,2],[3,3,3]])
x*y

array([[ 2,  4,  6],
       [12, 15, 18]])